version: '3.9'

services:
  app:
    build: .
    container_name: cas-management-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: mysql://user:password@mysql:3306/casdb
      SHADOW_DATABASE_URL: mysql://user:password@localhost:3306/casdb_shadow
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: cas-management-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: casdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: cas-management-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql

volumes:
  mysql_data:
